# 25/01/25 - Numpy datatypes

In [1]:
# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# S - string

In [11]:
import numpy as np
a=np.array([4,5,6,7,8]) # integer
# print(type(a))
print(a.dtype)

int32


In [12]:
a=np.array(['stalin','9','0']) #String
# print(type(a))
print(a.dtype)  # represent the unicode string(U) and return the maximum value of string is (6)--><U6

<U6


In [14]:
a=np.array([1.0,34.0,98.0]) #Float
print(a.dtype)

float64


In [19]:
a=np.array([1+3j]) #Complex
print(a.dtype)

complex128


# datatype converting

## 1.integer to string,float,complex

In [20]:
a=np.array([1,2,3,4,5],dtype="S")
print(a)
print(a.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [21]:
a=np.array([1,2,3,4,5],dtype="float")
print(a)
print(a.dtype)

[1. 2. 3. 4. 5.]
float64


In [22]:
a=np.array([1,2,3,4,5],dtype="complex")
print(a)
print(a.dtype)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]
complex128


## 2.string does not convert to any datatype

In [26]:
a=np.array(['1','sea','2'],dtype="i")
print(a)
print(a.dtype)  # does string convert to integer,float or complex

ValueError: invalid literal for int() with base 10: 'sea'

## 3.Float to int,String,complex

In [27]:
a=np.array([1.67,5.67,98.7],dtype="i")
print(a)
print(a.dtype)

[ 1  5 98]
int32


In [28]:
a=np.array([1.67,5.67,98.7],dtype="S")
print(a)
print(a.dtype)

[b'1.67' b'5.67' b'98.7']
|S4


In [29]:
a=np.array([1.67,5.67,98.7],dtype="complex")
print(a)
print(a.dtype)

[ 1.67+0.j  5.67+0.j 98.7 +0.j]
complex128


## 4.Complex  to int,String,float

In [30]:
a=np.array([1+3j,5+6j,9+1j],dtype="i")
print(a)
print(a.dtype)  #does not change to integer

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'complex'

In [31]:
a=np.array([1+3j,5+6j,9+1j],dtype="f")
print(a)
print(a.dtype) #does not change to float

TypeError: float() argument must be a string or a real number, not 'complex'

In [32]:
a=np.array([1+3j,5+6j,9+1j],dtype="S")
print(a)
print(a.dtype)

[b'(1+3j)' b'(5+6j)' b'(9+1j)']
|S6


# Numpy reshape

## 1d to 2d and 3d reshape

In [35]:
a=np.array([11,12,13,14,15,16,17,18,19,1,5,8,9,4,6,3])
print("1:",a.reshape(4,4))
print("2:",a.reshape(8,2))
print("3:",a.reshape(16,1))


1: [[11 12 13 14]
 [15 16 17 18]
 [19  1  5  8]
 [ 9  4  6  3]]
2: [[11 12]
 [13 14]
 [15 16]
 [17 18]
 [19  1]
 [ 5  8]
 [ 9  4]
 [ 6  3]]
3: [[11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [ 1]
 [ 5]
 [ 8]
 [ 9]
 [ 4]
 [ 6]
 [ 3]]


In [41]:
a=np.array([11,12,13,14,15,16,17,18,19,1,5,8,9,4,6,3])
print("1:",a.reshape(2,2,4))
print("2:",a.reshape(2,4,2))
print("3:",a.reshape(4,4,1))
print("3:",a.reshape(2,8,1))


1: [[[11 12 13 14]
  [15 16 17 18]]

 [[19  1  5  8]
  [ 9  4  6  3]]]
2: [[[11 12]
  [13 14]
  [15 16]
  [17 18]]

 [[19  1]
  [ 5  8]
  [ 9  4]
  [ 6  3]]]
3: [[[11]
  [12]
  [13]
  [14]]

 [[15]
  [16]
  [17]
  [18]]

 [[19]
  [ 1]
  [ 5]
  [ 8]]

 [[ 9]
  [ 4]
  [ 6]
  [ 3]]]
3: [[[11]
  [12]
  [13]
  [14]
  [15]
  [16]
  [17]
  [18]]

 [[19]
  [ 1]
  [ 5]
  [ 8]
  [ 9]
  [ 4]
  [ 6]
  [ 3]]]
