# 24/01/25 - Numpy 

In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
print(np.__version__)

1.26.4


# Dimensions array

In [4]:
# 1. 0-dimensional array
a=np.array(45)
print(a)

45


In [5]:
# 2. 1-dimensional array
a=np.array([1,2,3,4,5,6,7,])
print(a)

[1 2 3 4 5 6 7]


In [8]:
#. 2-dimensional array
a=np.array([[4,5,6,7,7],[2,5,7,9,0]])
print(a)

[[4 5 6 7 7]
 [2 5 7 9 0]]


In [9]:
# 4.3-dimensional array
a=np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]],[[12,13,14],[15,16,17]]])
print(a)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


# Numpy indexing

In [10]:
a=np.array([1,2,3,4,5,6,7,])
print(a[2])

3


In [26]:
a=np.array([[4,5,6,7,7],[2,5,7,9,0]])
print(a[1,2],a[0,2])


7 6


In [21]:
a=np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]],[[12,13,14],[15,16,17]]])
print(a[2,0,2],a[1,1,2])

14 11


# Slicing

In [3]:
import numpy as np
a=np.array([[4,5,6,7,7],[2,5,7,9,0]])
print(a[1,1:4])

[5 7 9]


In [15]:
a=np.array([[[4,5,6,7,8],[2,5,7,9,0]],[[1,2,3,4,5],[6,7,8,9,10]],[[12,45,67,83,25],[23,53,42,17,13]]])
print(a[0,1,1:4],a[1,0,0:4],a[2,1,-4:-1])

[5 7 9] [1 2 3 4] [53 42 17]


In [21]:
a=np.array([[1,2,3,4,5],[23,45,67,89,12],[9,8,34,21,18]])
print("Slicing:",a[1,1:4],a[0,1:],a[2,2:3])

Slicing: [45 67 89] [2 3 4 5] [34]
